version: "3.9"


services:

  my_web:
    build: .
    
    volumes:
      - ./data/sqlite:/usr/src/app/data/sqlite
      - ./data/media:/usr/src/app/data/media
      - ./logs/my_web:/usr/src/app/data/logs

    command: gunicorn core.wsgi:application -b 0.0.0.0:8000 --log-level=INFO --log-file=/usr/src/app/data/logs/my_web.log

  nginx:
    image: nginx:1.25.2

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/static_root:/code/static
      - ./data/media:/code/media
      
      - ./nginx/ssl:/etc/nginx/ssl
    
    depends_on:
      - my_web
    