version: "3.9"


services:

  my_web:
    build: .
    
    volumes:
      - ./my_web/sqlite:/usr/src/my_web/sqlite

  nginx:
    image: nginx:1.25.2

    ports:
      - "80:80"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static_root/:/code/static

    depends_on:
      - my_web
    