version: "3.9"


services:

  my_web:
    build: .
    
    volumes:
      - ./my_web/sqlite:/usr/src/my_web/sqlite

    command: python3 manage.py runserver 0.0.0.0:8000 --settings=core.settings.development

    ports:
      - "8000:8000"