version: "3.9"


services:

  my_web:
    build: .
    
    volumes:
      - ./my_web/sqlite:/usr/src/my_web/sqlite
      - ./my_web/media:/usr/src/my_web/media
      - ./logs/my_web:/usr/src/my_web/logs

    command: gunicorn core.wsgi:application -b 0.0.0.0:8000 --log-file=/usr/src/my_web/logs/my_web.log

  nginx:
    image: nginx:1.25.2

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static_root:/code/static
      - ./my_web/media:/code/media
      
      - ./nginx/ssl:/etc/nginx/ssl
    
    depends_on:
      - my_web
    