version: "3.9"


services:

  my_web:
    build: .
    
    volumes:
      - ./data/sqlite:/usr/src/app/data/sqlite
      - ./data/media:/usr/src/app/data/media

      - ./my_web:/usr/src/app/my_web

    command: python3 manage.py runserver 0.0.0.0:8000 --settings=core.settings.development

    ports:
      - "8000:8000"