# Generated by Django 4.1.4 on 2023-01-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woroked_for',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='img/enterprice/')),
            ],
        ),
        migrations.DeleteModel(
            name='Enterprice_listed',
        ),
        migrations.AlterField(
            model_name='programming_language',
            name='logo',
            field=models.ImageField(upload_to='img/lenguage/'),
        ),
    ]
