# Generated by Django 4.1.4 on 2023-01-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0002_woroked_for_delete_enterprice_listed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Woroked_for',
            new_name='Woroked_for_enterprice',
        ),
    ]
