# Generated by Django 4.1.4 on 2023-01-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0003_rename_woroked_for_woroked_for_enterprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming_language',
            name='logo',
            field=models.ImageField(upload_to='img/language/'),
        ),
    ]
