# Generated by Django 4.1.4 on 2023-01-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0004_alter_programming_language_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programming_language',
            new_name='My_tools',
        ),
    ]
