# Generated by Django 4.1.4 on 2023-01-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0005_rename_programming_language_my_tools'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
