# Generated by Django 4.1.4 on 2023-01-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0006_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_tools',
            new_name='My_tool',
        ),
    ]
