# Generated by Django 4.1.4 on 2023-01-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0007_rename_my_tools_my_tool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_tool',
            options={'verbose_name_plural': 'Mis herramientas'},
        ),
        migrations.AlterModelOptions(
            name='woroked_for_enterprice',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelTable(
            name='woroked_for_enterprice',
            table='Worked_for',
        ),
    ]
